# Workflow para construir e implantar um site Jekyll no GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Dispara o workflow em push para a branch main
  push:
    branches: ["main"]

  # Permite acionamento manual a partir da aba Actions
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Ajuste a versão conforme necessário

      - name: Install Jekyll and Bundler
        run: gem install jekyll bundler

      - name: Install dependencies
        run: |
          bundle init
          echo "gem 'jekyll'" >> Gemfile
          bundle install

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Build site with Jekyll
        run: bundle exec jekyll build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./_site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          path: ./_site
